/**
 * Bash 补全脚本模板
 */
export function generateBashTemplate(cliName: string): string {
  return `# ${cliName} bash completion
# Generated by ${cliName} completion command

_${cliName}_completion() {
  local cur prev words cword
  _init_completion || return

  # 获取动态补全建议（跳过第一个参数，即 CLI 名称）
  local suggestions
  suggestions=$(${cliName} __complete "\${words[@]:1}" 2>/dev/null)

  if [[ -n "\${suggestions}" ]]; then
    COMPREPLY=($(compgen -W "\${suggestions}" -- "\${cur}"))
  fi
}

complete -F _${cliName}_completion ${cliName}
`;
}

/**
 * Zsh 补全脚本模板
 */
export function generateZshTemplate(cliName: string): string {
  return `#compdef ${cliName}
# ${cliName} zsh completion
# Generated by ${cliName} completion command

_${cliName}() {
  local -a commands
  commands=(
    'help:显示帮助信息'
    'list:列出服务或工具'
    'call:调用 MCP 工具'
    'health:健康检查'
    'schema:导出工具 Schema'
    'config:配置管理'
    'skill:Skill 管理'
    'completion:生成 shell 补全脚本'
  )

  local context state line
  _arguments -C \\
    '(-d --detail)'{-d,--detail}'[显示详细输出]' \\
    '(-o --output)'{-o,--output}'[输出格式]:format:(json table text)' \\
    '(-p --profile)'{-p,--profile}'[环境配置]:profile' \\
    '(-c --config)'{-c,--config}'[配置文件路径]:file:_files' \\
    '(-t --timeout)'{-t,--timeout}'[请求超时时间]:seconds' \\
    '(-V --version)'{-V,--version}'[显示版本号]' \\
    '1: :->cmds' \\
    '2: :->args' \\
    '3: :->subargs'

  case $state in
    cmds)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
        list|health|schema)
          local -a servers
          servers=($(${cliName} __complete-servers 2>/dev/null))
          _describe 'server' servers
          ;;
        call)
          local -a servers
          servers=($(${cliName} __complete-servers 2>/dev/null))
          _describe 'server' servers
          ;;
        config)
          local -a actions
          actions=('init:初始化配置' 'show:显示配置' 'set:设置配置项')
          _describe 'action' actions
          if [[ $words[2] == init ]]; then
            _arguments '(-f --force)'{-f,--force}'[覆盖已有配置文件]'
          fi
          ;;
        skill)
          local -a actions
          actions=('install:安装 Skill')
          _describe 'action' actions
          ;;
        completion)
          local -a shells
          shells=('bash:Bash shell' 'zsh:Zsh shell' 'fish:Fish shell')
          _describe 'shell' shells
          ;;
      esac
      ;;
    subargs)
      case $words[1] in
        call)
          if [[ -n $words[2] ]]; then
            local -a tools
            tools=($(${cliName} __complete-tools $words[2] 2>/dev/null))
            _describe 'tool' tools
          fi
          ;;
      esac
      ;;
  esac
}

_${cliName}
`;
}

/**
 * Fish 补全脚本模板
 */
export function generateFishTemplate(cliName: string): string {
  return `# ${cliName} fish completion
# Generated by ${cliName} completion command

# Disable file completion by default
complete -c ${cliName} -f

# Global options
complete -c ${cliName} -s d -l detail -d '显示详细输出'
complete -c ${cliName} -s o -l output -d '输出格式' -xa 'json table text'
complete -c ${cliName} -s p -l profile -d '环境配置'
complete -c ${cliName} -s c -l config -d '配置文件路径' -r
complete -c ${cliName} -s t -l timeout -d '请求超时时间'
complete -c ${cliName} -s V -l version -d '显示版本号'

# Commands
complete -c ${cliName} -n __fish_use_subcommand -a help -d '显示帮助信息'
complete -c ${cliName} -n __fish_use_subcommand -a list -d '列出服务或工具'
complete -c ${cliName} -n __fish_use_subcommand -a call -d '调用 MCP 工具'
complete -c ${cliName} -n __fish_use_subcommand -a health -d '健康检查'
complete -c ${cliName} -n __fish_use_subcommand -a schema -d '导出工具 Schema'
complete -c ${cliName} -n __fish_use_subcommand -a config -d '配置管理'
complete -c ${cliName} -n __fish_use_subcommand -a skill -d 'Skill 管理'
complete -c ${cliName} -n __fish_use_subcommand -a completion -d '生成 shell 补全脚本'

# Dynamic server completion for list, health, schema, call
complete -c ${cliName} -n '__fish_seen_subcommand_from list' -a '(${cliName} __complete-servers 2>/dev/null)' -d '服务名称'
complete -c ${cliName} -n '__fish_seen_subcommand_from health' -a '(${cliName} __complete-servers 2>/dev/null)' -d '服务名称'
complete -c ${cliName} -n '__fish_seen_subcommand_from schema' -a '(${cliName} __complete-servers 2>/dev/null)' -d '服务名称'
complete -c ${cliName} -n '__fish_seen_subcommand_from call' -a '(${cliName} __complete-servers 2>/dev/null)' -d '服务名称'

# Tool completion for call command
complete -c ${cliName} -n '__fish_seen_subcommand_from call; and test (count (commandline -opc)) -eq 2' -a '(${cliName} __complete-tools (commandline -opc)[2] 2>/dev/null)' -d '工具名称'

# Config actions
complete -c ${cliName} -n '__fish_seen_subcommand_from config' -a init -d '初始化配置'
complete -c ${cliName} -n '__fish_seen_subcommand_from config' -a show -d '显示配置'
complete -c ${cliName} -n '__fish_seen_subcommand_from config' -a set -d '设置配置项'
complete -c ${cliName} -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from init' -l force -s f -d '覆盖已有配置'

# Skill actions
complete -c ${cliName} -n '__fish_seen_subcommand_from skill' -a install -d '安装 Skill'
complete -c ${cliName} -n '__fish_seen_subcommand_from skill' -l agent -s a -d '指定目标 Agent'
complete -c ${cliName} -n '__fish_seen_subcommand_from skill' -l dir -d '指定自定义 skills 根目录' -r
complete -c ${cliName} -n '__fish_seen_subcommand_from skill' -l force -s f -d '覆盖已有 Skill'

# Completion shells
complete -c ${cliName} -n '__fish_seen_subcommand_from completion' -a bash -d 'Bash shell'
complete -c ${cliName} -n '__fish_seen_subcommand_from completion' -a zsh -d 'Zsh shell'
complete -c ${cliName} -n '__fish_seen_subcommand_from completion' -a fish -d 'Fish shell'
`;
}